version: '3.8'

services:
  ai_api:
    build:
      context: .
      dockerfile: Dockerfile-tests
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    command: ["python", "app.py"]